/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'streakStart' : Time,
  'isDeepWork' : boolean,
  'streakType' : StreakType,
  'streakEnd' : Time,
  'milestone' : bigint,
}
export type AppCategory = { 'productive' : null } |
  { 'distracting' : null };
export interface BreakAnalysis {
  'walkBreaks' : bigint,
  'restorativeRatio' : number,
  'deskRecoveries' : bigint,
  'totalBreaks' : bigint,
}
export interface BreakSession {
  'startTime' : Time,
  'timerSetting' : TimerSetting,
  'endTime' : Time,
  'breakType' : BreakType,
  'isRestorative' : boolean,
}
export type BreakType = { 'walkBreak' : null } |
  { 'deskRecovery' : null };
export interface BurnoutCalculation {
  'currentIndex' : bigint,
  'focusSessionTimestamps' : Array<Time>,
  'switchCount' : bigint,
  'breakAnalysis' : BreakAnalysis,
  'timestamp' : Time,
  'sleepAnalysis' : SleepAnalysis,
  'notificationAnalysis' : NotificationAnalysis,
  'previousIndex' : bigint,
}
export interface ContextSwitch {
  'sourceApp' : string,
  'targetApp' : string,
  'timestamp' : Time,
}
export interface FocusScore {
  'distractingToProductive' : bigint,
  'distractionScore' : bigint,
  'productiveToProductive' : bigint,
  'timestamp' : Time,
  'productiveToDistracting' : bigint,
  'distractingToDistracting' : bigint,
  'timeAway' : bigint,
  'tabSwitchCount' : bigint,
}
export type NegativePattern = { 'distractionSpikes' : null } |
  { 'lateNightFatigue' : null } |
  { 'frequentSwitching' : null };
export interface NotificationAnalysis {
  'responseTimeAverage' : number,
  'frequency' : bigint,
}
export type Pattern = { 'negative' : NegativePattern } |
  { 'positive' : PositivePattern };
export type PositivePattern = { 'reducedDistractions' : null } |
  { 'workConsistency' : null } |
  { 'healthyBreaks' : null };
export interface Report { 'patterns' : Array<Pattern>, 'timestamp' : Time }
export interface Session {
  'duration' : bigint,
  'sessionType' : SessionType,
  'appName' : string,
  'timestamp' : Time,
  'category' : AppCategory,
}
export type SessionType = { 'focus' : null } |
  { 'rest' : null } |
  { 'distraction' : null };
export interface SleepAnalysis {
  'sleepDeficitScore' : number,
  'deepRestHours' : number,
  'totalSleepHours' : number,
}
export type StreakType = { 'deepWorkCompletion' : null } |
  { 'focusStreak' : null } |
  { 'distractionResistance' : null };
export type Time = bigint;
export interface TimerSetting { 'duration' : bigint, 'notification' : boolean }
export interface _SERVICE {
  'addAchievement' : ActorMethod<[Achievement], undefined>,
  'generateReport' : ActorMethod<[Array<Pattern>], Report>,
  'getAllBurnoutCalculations' : ActorMethod<
    [],
    Array<[Principal, Array<BurnoutCalculation>]>
  >,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getBurnoutCalculations' : ActorMethod<[], Array<BurnoutCalculation>>,
  'getFocusScores' : ActorMethod<[], Array<FocusScore>>,
  'getReportById' : ActorMethod<[bigint], [] | [Report]>,
  'recordBreak' : ActorMethod<[BreakSession], undefined>,
  'recordBurnoutCalculation' : ActorMethod<[BurnoutCalculation], undefined>,
  'recordContextSwitch' : ActorMethod<[], undefined>,
  'recordFocusScore' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'recordSession' : ActorMethod<[Session], undefined>,
  'recordSwitch' : ActorMethod<[ContextSwitch], undefined>,
  'startFocusSession' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];