/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const StreakType = IDL.Variant({
  'deepWorkCompletion' : IDL.Null,
  'focusStreak' : IDL.Null,
  'distractionResistance' : IDL.Null,
});
export const Achievement = IDL.Record({
  'streakStart' : Time,
  'isDeepWork' : IDL.Bool,
  'streakType' : StreakType,
  'streakEnd' : Time,
  'milestone' : IDL.Nat,
});
export const NegativePattern = IDL.Variant({
  'distractionSpikes' : IDL.Null,
  'lateNightFatigue' : IDL.Null,
  'frequentSwitching' : IDL.Null,
});
export const PositivePattern = IDL.Variant({
  'reducedDistractions' : IDL.Null,
  'workConsistency' : IDL.Null,
  'healthyBreaks' : IDL.Null,
});
export const Pattern = IDL.Variant({
  'negative' : NegativePattern,
  'positive' : PositivePattern,
});
export const Report = IDL.Record({
  'patterns' : IDL.Vec(Pattern),
  'timestamp' : Time,
});
export const TabType = IDL.Variant({
  'productive' : IDL.Null,
  'distractive' : IDL.Null,
});
export const FocusSessionViolation = IDL.Record({
  'sourceTab' : TabType,
  'targetTab' : TabType,
  'timestamp' : Time,
  'violationCount' : IDL.Nat,
});
export const FocusSessionData = IDL.Record({
  'duration' : IDL.Nat,
  'focusScore' : IDL.Nat,
  'completed' : IDL.Bool,
  'violations' : IDL.Vec(FocusSessionViolation),
  'timestamp' : Time,
});
export const FocusScore = IDL.Record({
  'distractionScore' : IDL.Nat,
  'timestamp' : Time,
  'timeAway' : IDL.Nat,
  'tabSwitchCount' : IDL.Nat,
});
export const TimerSetting = IDL.Record({
  'duration' : IDL.Nat,
  'notification' : IDL.Bool,
});
export const BreakType = IDL.Variant({
  'walkBreak' : IDL.Null,
  'deskRecovery' : IDL.Null,
});
export const BreakSession = IDL.Record({
  'startTime' : Time,
  'timerSetting' : TimerSetting,
  'endTime' : Time,
  'breakType' : BreakType,
  'isRestorative' : IDL.Bool,
});
export const SessionType = IDL.Variant({
  'focus' : IDL.Null,
  'rest' : IDL.Null,
  'distraction' : IDL.Null,
});
export const AppCategory = IDL.Variant({
  'productive' : IDL.Null,
  'distracting' : IDL.Null,
});
export const Session = IDL.Record({
  'duration' : IDL.Nat,
  'sessionType' : SessionType,
  'appName' : IDL.Text,
  'timestamp' : Time,
  'category' : AppCategory,
});
export const ContextSwitch = IDL.Record({
  'sourceApp' : IDL.Text,
  'targetApp' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addAchievement' : IDL.Func([Achievement], [], []),
  'generateReport' : IDL.Func([IDL.Vec(Pattern)], [Report], []),
  'getAllFocusSessions' : IDL.Func([], [IDL.Vec(FocusSessionData)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getFocusScores' : IDL.Func([], [IDL.Vec(FocusScore)], ['query']),
  'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'recordBreak' : IDL.Func([BreakSession], [], []),
  'recordFocusScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'recordFocusSession' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
  'recordSession' : IDL.Func([Session], [], []),
  'recordSwitch' : IDL.Func([ContextSwitch], [], []),
  'recordTabSwitch' : IDL.Func([TabType, TabType], [], []),
  'startFocusSession' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const StreakType = IDL.Variant({
    'deepWorkCompletion' : IDL.Null,
    'focusStreak' : IDL.Null,
    'distractionResistance' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'streakStart' : Time,
    'isDeepWork' : IDL.Bool,
    'streakType' : StreakType,
    'streakEnd' : Time,
    'milestone' : IDL.Nat,
  });
  const NegativePattern = IDL.Variant({
    'distractionSpikes' : IDL.Null,
    'lateNightFatigue' : IDL.Null,
    'frequentSwitching' : IDL.Null,
  });
  const PositivePattern = IDL.Variant({
    'reducedDistractions' : IDL.Null,
    'workConsistency' : IDL.Null,
    'healthyBreaks' : IDL.Null,
  });
  const Pattern = IDL.Variant({
    'negative' : NegativePattern,
    'positive' : PositivePattern,
  });
  const Report = IDL.Record({
    'patterns' : IDL.Vec(Pattern),
    'timestamp' : Time,
  });
  const TabType = IDL.Variant({
    'productive' : IDL.Null,
    'distractive' : IDL.Null,
  });
  const FocusSessionViolation = IDL.Record({
    'sourceTab' : TabType,
    'targetTab' : TabType,
    'timestamp' : Time,
    'violationCount' : IDL.Nat,
  });
  const FocusSessionData = IDL.Record({
    'duration' : IDL.Nat,
    'focusScore' : IDL.Nat,
    'completed' : IDL.Bool,
    'violations' : IDL.Vec(FocusSessionViolation),
    'timestamp' : Time,
  });
  const FocusScore = IDL.Record({
    'distractionScore' : IDL.Nat,
    'timestamp' : Time,
    'timeAway' : IDL.Nat,
    'tabSwitchCount' : IDL.Nat,
  });
  const TimerSetting = IDL.Record({
    'duration' : IDL.Nat,
    'notification' : IDL.Bool,
  });
  const BreakType = IDL.Variant({
    'walkBreak' : IDL.Null,
    'deskRecovery' : IDL.Null,
  });
  const BreakSession = IDL.Record({
    'startTime' : Time,
    'timerSetting' : TimerSetting,
    'endTime' : Time,
    'breakType' : BreakType,
    'isRestorative' : IDL.Bool,
  });
  const SessionType = IDL.Variant({
    'focus' : IDL.Null,
    'rest' : IDL.Null,
    'distraction' : IDL.Null,
  });
  const AppCategory = IDL.Variant({
    'productive' : IDL.Null,
    'distracting' : IDL.Null,
  });
  const Session = IDL.Record({
    'duration' : IDL.Nat,
    'sessionType' : SessionType,
    'appName' : IDL.Text,
    'timestamp' : Time,
    'category' : AppCategory,
  });
  const ContextSwitch = IDL.Record({
    'sourceApp' : IDL.Text,
    'targetApp' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addAchievement' : IDL.Func([Achievement], [], []),
    'generateReport' : IDL.Func([IDL.Vec(Pattern)], [Report], []),
    'getAllFocusSessions' : IDL.Func(
        [],
        [IDL.Vec(FocusSessionData)],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getFocusScores' : IDL.Func([], [IDL.Vec(FocusScore)], ['query']),
    'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'recordBreak' : IDL.Func([BreakSession], [], []),
    'recordFocusScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'recordFocusSession' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
    'recordSession' : IDL.Func([Session], [], []),
    'recordSwitch' : IDL.Func([ContextSwitch], [], []),
    'recordTabSwitch' : IDL.Func([TabType, TabType], [], []),
    'startFocusSession' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };