/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'productive' : IDL.Null,
  'distracting' : IDL.Null,
  'neutral' : IDL.Null,
});
export const ActivitySwitch = IDL.Record({
  'toApp' : IDL.Text,
  'toCategory' : Category,
  'fromCategory' : Category,
  'fromApp' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SourceType = IDL.Variant({
  'other' : IDL.Null,
  'news' : IDL.Null,
  'workApp' : IDL.Null,
  'shopping' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const DistractionLog = IDL.Record({
  'source' : IDL.Text,
  'description' : IDL.Text,
  'sourceType' : SourceType,
  'timestamp' : IDL.Int,
  'category' : Category,
});
export const SessionSummary = IDL.Record({
  'startTime' : IDL.Int,
  'productiveTime' : IDL.Nat,
  'endTime' : IDL.Int,
  'totalDuration' : IDL.Int,
  'distractingTime' : IDL.Nat,
  'burnoutScore' : IDL.Int,
  'sessionId' : IDL.Nat,
  'switchesCount' : IDL.Nat,
  'distractionsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'endSession' : IDL.Func([], [], []),
  'getActivitySwitches' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ActivitySwitch))],
      ['query'],
    ),
  'getAllAppCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Category))],
      ['query'],
    ),
  'getAppCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getCurrentSessionStats' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getDistractionLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DistractionLog))],
      ['query'],
    ),
  'getLongestFocusStreak' : IDL.Func([], [IDL.Int], ['query']),
  'getMostFrequentDistractions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getSessionHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SessionSummary)],
      ['query'],
    ),
  'getSessionSummaries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, SessionSummary))],
      ['query'],
    ),
  'logDistraction' : IDL.Func(
      [IDL.Text, Category, SourceType, IDL.Text],
      [],
      [],
    ),
  'recordActivitySwitch' : IDL.Func(
      [IDL.Text, IDL.Text, Category, Category],
      [],
      [],
    ),
  'recordTimeBlock' : IDL.Func([Category, IDL.Int], [], []),
  'setAppCategory' : IDL.Func([IDL.Text, Category], [], []),
  'startSession' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'productive' : IDL.Null,
    'distracting' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const ActivitySwitch = IDL.Record({
    'toApp' : IDL.Text,
    'toCategory' : Category,
    'fromCategory' : Category,
    'fromApp' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SourceType = IDL.Variant({
    'other' : IDL.Null,
    'news' : IDL.Null,
    'workApp' : IDL.Null,
    'shopping' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const DistractionLog = IDL.Record({
    'source' : IDL.Text,
    'description' : IDL.Text,
    'sourceType' : SourceType,
    'timestamp' : IDL.Int,
    'category' : Category,
  });
  const SessionSummary = IDL.Record({
    'startTime' : IDL.Int,
    'productiveTime' : IDL.Nat,
    'endTime' : IDL.Int,
    'totalDuration' : IDL.Int,
    'distractingTime' : IDL.Nat,
    'burnoutScore' : IDL.Int,
    'sessionId' : IDL.Nat,
    'switchesCount' : IDL.Nat,
    'distractionsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'endSession' : IDL.Func([], [], []),
    'getActivitySwitches' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ActivitySwitch))],
        ['query'],
      ),
    'getAllAppCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Category))],
        ['query'],
      ),
    'getAppCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getCurrentSessionStats' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getDistractionLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DistractionLog))],
        ['query'],
      ),
    'getLongestFocusStreak' : IDL.Func([], [IDL.Int], ['query']),
    'getMostFrequentDistractions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getSessionHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionSummary)],
        ['query'],
      ),
    'getSessionSummaries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, SessionSummary))],
        ['query'],
      ),
    'logDistraction' : IDL.Func(
        [IDL.Text, Category, SourceType, IDL.Text],
        [],
        [],
      ),
    'recordActivitySwitch' : IDL.Func(
        [IDL.Text, IDL.Text, Category, Category],
        [],
        [],
      ),
    'recordTimeBlock' : IDL.Func([Category, IDL.Int], [], []),
    'setAppCategory' : IDL.Func([IDL.Text, Category], [], []),
    'startSession' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };