/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivitySwitch {
  'toApp' : string,
  'toCategory' : Category,
  'fromCategory' : Category,
  'fromApp' : string,
  'timestamp' : bigint,
}
export type Category = { 'productive' : null } |
  { 'distracting' : null } |
  { 'neutral' : null };
export interface DistractionLog {
  'source' : string,
  'description' : string,
  'sourceType' : SourceType,
  'timestamp' : bigint,
  'category' : Category,
}
export interface SessionSummary {
  'startTime' : bigint,
  'productiveTime' : bigint,
  'endTime' : bigint,
  'totalDuration' : bigint,
  'distractingTime' : bigint,
  'burnoutScore' : bigint,
  'sessionId' : bigint,
  'switchesCount' : bigint,
  'distractionsCount' : bigint,
}
export type SourceType = { 'other' : null } |
  { 'news' : null } |
  { 'workApp' : null } |
  { 'shopping' : null } |
  { 'socialMedia' : null };
export interface _SERVICE {
  'endSession' : ActorMethod<[], undefined>,
  'getActivitySwitches' : ActorMethod<[], Array<[bigint, ActivitySwitch]>>,
  'getAllAppCategories' : ActorMethod<[], Array<[string, Category]>>,
  'getAppCategory' : ActorMethod<[string], [] | [Category]>,
  'getCurrentSessionStats' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint]
  >,
  'getDistractionLogs' : ActorMethod<[], Array<[bigint, DistractionLog]>>,
  'getLongestFocusStreak' : ActorMethod<[], bigint>,
  'getMostFrequentDistractions' : ActorMethod<[], Array<[string, bigint]>>,
  'getSessionHistory' : ActorMethod<[string], Array<SessionSummary>>,
  'getSessionSummaries' : ActorMethod<[], Array<[bigint, SessionSummary]>>,
  'logDistraction' : ActorMethod<
    [string, Category, SourceType, string],
    undefined
  >,
  'recordActivitySwitch' : ActorMethod<
    [string, string, Category, Category],
    undefined
  >,
  'recordTimeBlock' : ActorMethod<[Category, bigint], undefined>,
  'setAppCategory' : ActorMethod<[string, Category], undefined>,
  'startSession' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];