/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimerSetting {
    duration: bigint;
    notification: boolean;
}
export type Time = bigint;
export interface Report {
    patterns: Array<Pattern>;
    timestamp: Time;
}
export interface Achievement {
    streakStart: Time;
    isDeepWork: boolean;
    streakType: StreakType;
    streakEnd: Time;
    milestone: bigint;
}
export interface Session {
    duration: bigint;
    sessionType: SessionType;
    appName: string;
    timestamp: Time;
    category: AppCategory;
}
export type Pattern = {
    __kind__: "negative";
    negative: NegativePattern;
} | {
    __kind__: "positive";
    positive: PositivePattern;
};
export interface ContextSwitch {
    sourceApp: string;
    targetApp: string;
    timestamp: Time;
}
export interface BreakSession {
    startTime: Time;
    timerSetting: TimerSetting;
    endTime: Time;
    breakType: BreakType;
    isRestorative: boolean;
}
export enum AppCategory {
    productive = "productive",
    distracting = "distracting"
}
export enum BreakType {
    walkBreak = "walkBreak",
    deskRecovery = "deskRecovery"
}
export enum NegativePattern {
    distractionSpikes = "distractionSpikes",
    lateNightFatigue = "lateNightFatigue",
    frequentSwitching = "frequentSwitching"
}
export enum PositivePattern {
    reducedDistractions = "reducedDistractions",
    workConsistency = "workConsistency",
    healthyBreaks = "healthyBreaks"
}
export enum SessionType {
    focus = "focus",
    rest = "rest",
    distraction = "distraction"
}
export enum StreakType {
    deepWorkCompletion = "deepWorkCompletion",
    focusStreak = "focusStreak",
    distractionResistance = "distractionResistance"
}
export interface backendInterface {
    addAchievement(achievement: Achievement): Promise<void>;
    generateReport(patterns: Array<Pattern>): Promise<Report>;
    getAllReports(): Promise<Array<Report>>;
    getReportById(reportId: bigint): Promise<Report>;
    recordBreak(breakSession: BreakSession): Promise<void>;
    recordContextSwitch(): Promise<void>;
    recordSession(session: Session): Promise<void>;
    recordSwitch(contextSwitch: ContextSwitch): Promise<void>;
}
import type { Achievement as _Achievement, AppCategory as _AppCategory, BreakSession as _BreakSession, BreakType as _BreakType, NegativePattern as _NegativePattern, Pattern as _Pattern, PositivePattern as _PositivePattern, Report as _Report, Session as _Session, SessionType as _SessionType, StreakType as _StreakType, Time as _Time, TimerSetting as _TimerSetting } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAchievement(arg0: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(to_candid_Achievement_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(to_candid_Achievement_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateReport(arg0: Array<Pattern>): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Report_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Report_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportById(arg0: bigint): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportById(arg0);
                return from_candid_Report_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportById(arg0);
            return from_candid_Report_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordBreak(arg0: BreakSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBreak(to_candid_BreakSession_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBreak(to_candid_BreakSession_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordContextSwitch(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordContextSwitch();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordContextSwitch();
            return result;
        }
    }
    async recordSession(arg0: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSession(to_candid_Session_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSession(to_candid_Session_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordSwitch(arg0: ContextSwitch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSwitch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSwitch(arg0);
            return result;
        }
    }
}
function from_candid_NegativePattern_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NegativePattern): NegativePattern {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Pattern_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pattern): Pattern {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PositivePattern_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositivePattern): PositivePattern {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patterns: Array<_Pattern>;
    timestamp: _Time;
}): {
    patterns: Array<Pattern>;
    timestamp: Time;
} {
    return {
        patterns: from_candid_vec_n14(_uploadFile, _downloadFile, value.patterns),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negative: _NegativePattern;
} | {
    positive: _PositivePattern;
}): {
    __kind__: "negative";
    negative: NegativePattern;
} | {
    __kind__: "positive";
    positive: PositivePattern;
} {
    return "negative" in value ? {
        __kind__: "negative",
        negative: from_candid_NegativePattern_n17(_uploadFile, _downloadFile, value.negative)
    } : "positive" in value ? {
        __kind__: "positive",
        positive: from_candid_PositivePattern_n19(_uploadFile, _downloadFile, value.positive)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distractionSpikes: null;
} | {
    lateNightFatigue: null;
} | {
    frequentSwitching: null;
}): NegativePattern {
    return "distractionSpikes" in value ? NegativePattern.distractionSpikes : "lateNightFatigue" in value ? NegativePattern.lateNightFatigue : "frequentSwitching" in value ? NegativePattern.frequentSwitching : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reducedDistractions: null;
} | {
    workConsistency: null;
} | {
    healthyBreaks: null;
}): PositivePattern {
    return "reducedDistractions" in value ? PositivePattern.reducedDistractions : "workConsistency" in value ? PositivePattern.workConsistency : "healthyBreaks" in value ? PositivePattern.healthyBreaks : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pattern>): Array<Pattern> {
    return value.map((x)=>from_candid_Pattern_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Achievement_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Achievement): _Achievement {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AppCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): _AppCategory {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_BreakSession_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BreakSession): _BreakSession {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_BreakType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BreakType): _BreakType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_NegativePattern_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NegativePattern): _NegativePattern {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Pattern_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pattern): _Pattern {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PositivePattern_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositivePattern): _PositivePattern {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StreakType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StreakType): _StreakType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streakStart: Time;
    isDeepWork: boolean;
    streakType: StreakType;
    streakEnd: Time;
    milestone: bigint;
}): {
    streakStart: _Time;
    isDeepWork: boolean;
    streakType: _StreakType;
    streakEnd: _Time;
    milestone: bigint;
} {
    return {
        streakStart: value.streakStart,
        isDeepWork: value.isDeepWork,
        streakType: to_candid_StreakType_n3(_uploadFile, _downloadFile, value.streakType),
        streakEnd: value.streakEnd,
        milestone: value.milestone
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Time;
    timerSetting: TimerSetting;
    endTime: Time;
    breakType: BreakType;
    isRestorative: boolean;
}): {
    startTime: _Time;
    timerSetting: _TimerSetting;
    endTime: _Time;
    breakType: _BreakType;
    isRestorative: boolean;
} {
    return {
        startTime: value.startTime,
        timerSetting: value.timerSetting,
        endTime: value.endTime,
        breakType: to_candid_BreakType_n24(_uploadFile, _downloadFile, value.breakType),
        isRestorative: value.isRestorative
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    sessionType: SessionType;
    appName: string;
    timestamp: Time;
    category: AppCategory;
}): {
    duration: bigint;
    sessionType: _SessionType;
    appName: string;
    timestamp: _Time;
    category: _AppCategory;
} {
    return {
        duration: value.duration,
        sessionType: to_candid_SessionType_n28(_uploadFile, _downloadFile, value.sessionType),
        appName: value.appName,
        timestamp: value.timestamp,
        category: to_candid_AppCategory_n30(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NegativePattern): {
    distractionSpikes: null;
} | {
    lateNightFatigue: null;
} | {
    frequentSwitching: null;
} {
    return value == NegativePattern.distractionSpikes ? {
        distractionSpikes: null
    } : value == NegativePattern.lateNightFatigue ? {
        lateNightFatigue: null
    } : value == NegativePattern.frequentSwitching ? {
        frequentSwitching: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BreakType): {
    walkBreak: null;
} | {
    deskRecovery: null;
} {
    return value == BreakType.walkBreak ? {
        walkBreak: null
    } : value == BreakType.deskRecovery ? {
        deskRecovery: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    focus: null;
} | {
    rest: null;
} | {
    distraction: null;
} {
    return value == SessionType.focus ? {
        focus: null
    } : value == SessionType.rest ? {
        rest: null
    } : value == SessionType.distraction ? {
        distraction: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): {
    productive: null;
} | {
    distracting: null;
} {
    return value == AppCategory.productive ? {
        productive: null
    } : value == AppCategory.distracting ? {
        distracting: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StreakType): {
    deepWorkCompletion: null;
} | {
    focusStreak: null;
} | {
    distractionResistance: null;
} {
    return value == StreakType.deepWorkCompletion ? {
        deepWorkCompletion: null
    } : value == StreakType.focusStreak ? {
        focusStreak: null
    } : value == StreakType.distractionResistance ? {
        distractionResistance: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "negative";
    negative: NegativePattern;
} | {
    __kind__: "positive";
    positive: PositivePattern;
}): {
    negative: _NegativePattern;
} | {
    positive: _PositivePattern;
} {
    return value.__kind__ === "negative" ? {
        negative: to_candid_NegativePattern_n10(_uploadFile, _downloadFile, value.negative)
    } : value.__kind__ === "positive" ? {
        positive: to_candid_PositivePattern_n8(_uploadFile, _downloadFile, value.positive)
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositivePattern): {
    reducedDistractions: null;
} | {
    workConsistency: null;
} | {
    healthyBreaks: null;
} {
    return value == PositivePattern.reducedDistractions ? {
        reducedDistractions: null
    } : value == PositivePattern.workConsistency ? {
        workConsistency: null
    } : value == PositivePattern.healthyBreaks ? {
        healthyBreaks: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Pattern>): Array<_Pattern> {
    return value.map((x)=>to_candid_Pattern_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
