/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DistractionLog {
    source: string;
    description: string;
    sourceType: SourceType;
    timestamp: bigint;
    category: Category;
}
export interface ActivitySwitch {
    toApp: string;
    toCategory: Category;
    fromCategory: Category;
    fromApp: string;
    timestamp: bigint;
}
export interface SessionSummary {
    startTime: bigint;
    productiveTime: bigint;
    endTime: bigint;
    totalDuration: bigint;
    distractingTime: bigint;
    burnoutScore: bigint;
    sessionId: bigint;
    switchesCount: bigint;
    distractionsCount: bigint;
}
export enum Category {
    productive = "productive",
    distracting = "distracting",
    neutral = "neutral"
}
export enum SourceType {
    other = "other",
    news = "news",
    workApp = "workApp",
    shopping = "shopping",
    socialMedia = "socialMedia"
}
export interface backendInterface {
    endSession(): Promise<void>;
    getActivitySwitches(): Promise<Array<[bigint, ActivitySwitch]>>;
    getAllAppCategories(): Promise<Array<[string, Category]>>;
    getAppCategory(appName: string): Promise<Category | null>;
    getCurrentSessionStats(): Promise<[bigint, bigint, bigint, bigint, bigint]>;
    getDistractionLogs(): Promise<Array<[bigint, DistractionLog]>>;
    getLongestFocusStreak(): Promise<bigint>;
    getMostFrequentDistractions(): Promise<Array<[string, bigint]>>;
    getSessionHistory(sortBy: string): Promise<Array<SessionSummary>>;
    getSessionSummaries(): Promise<Array<[bigint, SessionSummary]>>;
    logDistraction(source: string, category: Category, sourceType: SourceType, description: string): Promise<void>;
    recordActivitySwitch(fromApp: string, toApp: string, fromCategory: Category, toCategory: Category): Promise<void>;
    recordTimeBlock(category: Category, duration: bigint): Promise<void>;
    setAppCategory(appName: string, category: Category): Promise<void>;
    startSession(): Promise<void>;
}
import type { ActivitySwitch as _ActivitySwitch, Category as _Category, DistractionLog as _DistractionLog, SourceType as _SourceType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async endSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession();
            return result;
        }
    }
    async getActivitySwitches(): Promise<Array<[bigint, ActivitySwitch]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitySwitches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitySwitches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAppCategories(): Promise<Array<[string, Category]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppCategories();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppCategories();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppCategory(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppCategory(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentSessionStats(): Promise<[bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentSessionStats();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentSessionStats();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getDistractionLogs(): Promise<Array<[bigint, DistractionLog]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistractionLogs();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistractionLogs();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLongestFocusStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLongestFocusStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLongestFocusStreak();
            return result;
        }
    }
    async getMostFrequentDistractions(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostFrequentDistractions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostFrequentDistractions();
            return result;
        }
    }
    async getSessionHistory(arg0: string): Promise<Array<SessionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionHistory(arg0);
            return result;
        }
    }
    async getSessionSummaries(): Promise<Array<[bigint, SessionSummary]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionSummaries();
            return result;
        }
    }
    async logDistraction(arg0: string, arg1: Category, arg2: SourceType, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDistraction(arg0, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg1), to_candid_SourceType_n18(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDistraction(arg0, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg1), to_candid_SourceType_n18(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async recordActivitySwitch(arg0: string, arg1: string, arg2: Category, arg3: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordActivitySwitch(arg0, arg1, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n16(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordActivitySwitch(arg0, arg1, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n16(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async recordTimeBlock(arg0: Category, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTimeBlock(to_candid_Category_n16(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTimeBlock(to_candid_Category_n16(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async setAppCategory(arg0: string, arg1: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppCategory(arg0, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppCategory(arg0, to_candid_Category_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async startSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession();
            return result;
        }
    }
}
function from_candid_ActivitySwitch_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivitySwitch): ActivitySwitch {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DistractionLog_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistractionLog): DistractionLog {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SourceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceType): SourceType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: string;
    description: string;
    sourceType: _SourceType;
    timestamp: bigint;
    category: _Category;
}): {
    source: string;
    description: string;
    sourceType: SourceType;
    timestamp: bigint;
    category: Category;
} {
    return {
        source: value.source,
        description: value.description,
        sourceType: from_candid_SourceType_n14(_uploadFile, _downloadFile, value.sourceType),
        timestamp: value.timestamp,
        category: from_candid_Category_n5(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toApp: string;
    toCategory: _Category;
    fromCategory: _Category;
    fromApp: string;
    timestamp: bigint;
}): {
    toApp: string;
    toCategory: Category;
    fromCategory: Category;
    fromApp: string;
    timestamp: bigint;
} {
    return {
        toApp: value.toApp,
        toCategory: from_candid_Category_n5(_uploadFile, _downloadFile, value.toCategory),
        fromCategory: from_candid_Category_n5(_uploadFile, _downloadFile, value.fromCategory),
        fromApp: value.fromApp,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _DistractionLog]): [bigint, DistractionLog] {
    return [
        value[0],
        from_candid_DistractionLog_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ActivitySwitch]): [bigint, ActivitySwitch] {
    return [
        value[0],
        from_candid_ActivitySwitch_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Category]): [string, Category] {
    return [
        value[0],
        from_candid_Category_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    news: null;
} | {
    workApp: null;
} | {
    shopping: null;
} | {
    socialMedia: null;
}): SourceType {
    return "other" in value ? SourceType.other : "news" in value ? SourceType.news : "workApp" in value ? SourceType.workApp : "shopping" in value ? SourceType.shopping : "socialMedia" in value ? SourceType.socialMedia : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productive: null;
} | {
    distracting: null;
} | {
    neutral: null;
}): Category {
    return "productive" in value ? Category.productive : "distracting" in value ? Category.distracting : "neutral" in value ? Category.neutral : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ActivitySwitch]>): Array<[bigint, ActivitySwitch]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _DistractionLog]>): Array<[bigint, DistractionLog]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Category]>): Array<[string, Category]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SourceType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceType): _SourceType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    productive: null;
} | {
    distracting: null;
} | {
    neutral: null;
} {
    return value == Category.productive ? {
        productive: null
    } : value == Category.distracting ? {
        distracting: null
    } : value == Category.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceType): {
    other: null;
} | {
    news: null;
} | {
    workApp: null;
} | {
    shopping: null;
} | {
    socialMedia: null;
} {
    return value == SourceType.other ? {
        other: null
    } : value == SourceType.news ? {
        news: null
    } : value == SourceType.workApp ? {
        workApp: null
    } : value == SourceType.shopping ? {
        shopping: null
    } : value == SourceType.socialMedia ? {
        socialMedia: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
